/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SzervezzRouteImport } from './routes/szervezz'
import { Route as ProgramokRouteImport } from './routes/programok'
import { Route as PrivatRouteImport } from './routes/privat'
import { Route as KapcsolatRouteImport } from './routes/kapcsolat'
import { Route as AHelyRouteImport } from './routes/a-hely'
import { Route as IndexRouteImport } from './routes/index'

const SzervezzRoute = SzervezzRouteImport.update({
  id: '/szervezz',
  path: '/szervezz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramokRoute = ProgramokRouteImport.update({
  id: '/programok',
  path: '/programok',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatRoute = PrivatRouteImport.update({
  id: '/privat',
  path: '/privat',
  getParentRoute: () => rootRouteImport,
} as any)
const KapcsolatRoute = KapcsolatRouteImport.update({
  id: '/kapcsolat',
  path: '/kapcsolat',
  getParentRoute: () => rootRouteImport,
} as any)
const AHelyRoute = AHelyRouteImport.update({
  id: '/a-hely',
  path: '/a-hely',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-hely': typeof AHelyRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/privat': typeof PrivatRoute
  '/programok': typeof ProgramokRoute
  '/szervezz': typeof SzervezzRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-hely': typeof AHelyRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/privat': typeof PrivatRoute
  '/programok': typeof ProgramokRoute
  '/szervezz': typeof SzervezzRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-hely': typeof AHelyRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/privat': typeof PrivatRoute
  '/programok': typeof ProgramokRoute
  '/szervezz': typeof SzervezzRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-hely'
    | '/kapcsolat'
    | '/privat'
    | '/programok'
    | '/szervezz'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/a-hely' | '/kapcsolat' | '/privat' | '/programok' | '/szervezz'
  id:
    | '__root__'
    | '/'
    | '/a-hely'
    | '/kapcsolat'
    | '/privat'
    | '/programok'
    | '/szervezz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AHelyRoute: typeof AHelyRoute
  KapcsolatRoute: typeof KapcsolatRoute
  PrivatRoute: typeof PrivatRoute
  ProgramokRoute: typeof ProgramokRoute
  SzervezzRoute: typeof SzervezzRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/szervezz': {
      id: '/szervezz'
      path: '/szervezz'
      fullPath: '/szervezz'
      preLoaderRoute: typeof SzervezzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programok': {
      id: '/programok'
      path: '/programok'
      fullPath: '/programok'
      preLoaderRoute: typeof ProgramokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privat': {
      id: '/privat'
      path: '/privat'
      fullPath: '/privat'
      preLoaderRoute: typeof PrivatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapcsolat': {
      id: '/kapcsolat'
      path: '/kapcsolat'
      fullPath: '/kapcsolat'
      preLoaderRoute: typeof KapcsolatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-hely': {
      id: '/a-hely'
      path: '/a-hely'
      fullPath: '/a-hely'
      preLoaderRoute: typeof AHelyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AHelyRoute: AHelyRoute,
  KapcsolatRoute: KapcsolatRoute,
  PrivatRoute: PrivatRoute,
  ProgramokRoute: ProgramokRoute,
  SzervezzRoute: SzervezzRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
